package com.mycompany.kwn_edu.models;
// Generated Jun 23, 2017 5:52:36 PM by Hibernate Tools 4.3.1



/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private int id;
     private User user;
     private String role;

    public Role() {
    }

    public Role(int id, User user, String role) {
       this.id = id;
       this.user = user;
       this.role = role;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


