package com.mycompany.kwn_edu.models;
// Generated Jun 26, 2017 12:20:53 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test",
         catalog = "test_hibernate"
)
public class Test implements java.io.Serializable {

    private int id;
    private String name;

    public Test() {
    }

    public Test(int id) {
        this.id = id;
    }

    public Test(int id, String name) {
        this.id = id;
        this.name = name;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
