package com.mycompany.kwn_edu.models;
// Generated Jun 23, 2017 5:52:36 PM by Hibernate Tools 4.3.1



/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private int id;
     private String name;

    public Test() {
    }

	
    public Test(int id) {
        this.id = id;
    }
    public Test(int id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


