package com.mycompany.kwn_edu.models;
// Generated Jun 23, 2017 5:52:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String email;
     private String password;
     private Set<Role> roles = new HashSet(0);

    public User() {
    }

	
    public User(String email, String password) {
        this.email = email;
        this.password = password;
    }
    public User(String email, String password, Set roles) {
       this.email = email;
       this.password = password;
       this.roles = roles;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }




}


